pipeline {
    agent any

    environment {
        REGISTRY_PASSWORD_1 = credentials('REGISTRY_PASSWORD_1')
        group='rg-devops-sura-jah1-dev'
        location='southcentralus'
        registry='crdevopssurajah1dev'
        registry_url='https://crdevopssurajah1dev.azurecr.io'
        skuRegistry='Basic'
        plan='plan-devops-sura-jah1-dev'
        app='app-devops-sura-starter-jah1-dev'
        image='crdevopssurajah1dev.azurecr.io/starter:latest'
    }

    stages {
        stage('Build ') {
            steps {
                //
                echo 'Building'
                sh 'sudo apt-get update -y'
                sh 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh 'rm -rf fe-devops-sura-jah1-dev'
                    sh 'npx gatsby new fe-devops-sura-jah1-dev https://github.com/Evaluates2/Gatsby-Starter-TypeScript-Redux-TDD-BDD'
                    sh 'npm run build --prefix fe-devops-sura-jah1-dev'
                }
            }
        }
        stage('Test') { 
            steps {
                // 
                echo 'Testing'
                nodejs(nodeJSInstallationName: 'Node 12.22.3') {
                    sh 'npm run test-once --prefix fe-devops-sura-jah1-dev'
                    sh 'npm run lint --prefix fe-devops-sura-jah1-dev'
                }
            }
        }
        stage('Deploy') {
            steps {
                //
                echo 'Deploying'
                withCredentials([azureServicePrincipal('0b7e2298-6466-47e3-8b0d-99c37b8c9cdc')]) {
                  sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                  sh '''
cat <<-EOF>> fe-devops-sura-jah1-dev/Dockerfile
FROM nginx:stable-alpine
COPY public /usr/share/nginx/html
EXPOSE 80
CMD ]"nginx", "-g", "daemon off"]
EOF'''
                    sh 'docker build -f fe-devops-sura-jah1-dev/Dockerfile -t $image fe-devops-sura-jah1-dev'
                    sh 'docker login $registry_url -u crdevopssurajah1dev -p $REGISTRY_PASSWORD_1'
                    sh 'docker push $image'
                    sh 'az configure --defaults group=$group location=$location'
                    sh 'az webapp create --plan $plan --name $app --development-container-image-name $image'
                    sh 'az webapp config container set --name $app --docker-custom-image-name $image --docker-registry-server-url $registry_url'
                }
            }
        }
    }
}
